#!/bin/bash
# JankyBorders — bordure autour de la fenêtre active (Catppuccin Mocha)
# Recharger : brew services restart borders
options=(
  style=round
  width=8.0
  hidpi=on
  #active_color=0xffcba6f7    # mauve
  active_color=0xff39ff14
  #inactive_color=0x00000000  # invisible
  inactive_color=0xff6c7086
)
borders "${options[@]}"
